spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Orange-66/springcloud-config.git
          username: Orange-66
          password: shilichunfeng66
      label: master

server:
  port: 7755
